[book]
title = "WeaveFFI"
authors = ["WeaveFFI maintainers"]
language = "en"
multilingual = false

[build]
create-missing = true

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/weaveffi/weaveffi"
site-url = "https://docs.weaveffi.com/"
